version: '3.8'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: store-api
    restart: no
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: api-nginx
    restart: no
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
  db:
    container_name: mysql_store
    image: mysql:8.0
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./storage/mysql:/var/lib/mysql
      - ./init/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    ports: 
      - 3306:3306